language: java8
jdk:
  - oraclejdk8
script: mvn install

deploy:
   edge: true
   provider: cloudfoundry
   username: jan.gertgens@novatec-gmbh.de
   password: Lots1*GoyiSejc
   api: https://api.run.pivotal.io
   organization: jan.gertgens.org
   space: devlopment