language: java8
jdk:
  - oraclejdk8
sudo: required
install:
  - sudo apt-get install -y linux-image-virtual kernel linux-image-extra-virtual
  - curl -sSL https://get.docker.com/ | sudo sh

script: sudo mvn clean package docker:build

