language: java8
jdk:
  - oraclejdk8
script: mvn verify

deploy:
   edge: true
   provider: cloudfoundry
   username: jan.gertgens@novatec-gmbh.de
   password: Gamg9-QuyeCapm
   api: https://api.run.pivotal.io
   organization: jan.gertgens.org
   space: devlopment